
continuewithGoogle: 'css:button:has-text("GGGGGG|authorize.ContinuewithGoogle|GGGGGG")'

continuewithGitHub: 'css:button:has-text("GGGGGG|authorize.ContinuewithGitHub|GGGGGG")'
gitHubUserNameOrEmailAddress: 'css:#login_field'
gitHubPassword: 'css:#password'
gitHubsignIn: 'css:input[value="Sign in"]'
gitHubVerificationCodeInput: 'css:#otp'
gitHubVerify: 'css:button[type="submit"]'


continuewithEmail: 'css:button:has-text("GGGGGG|authorize.ContinuewithEmail|GGGGGG")'
emailAddress: 'css:#email'
verifyCodeInput: 'css:.flex.w-full.flex-col>.flex.flex-row>input'

continueWithEnterpriseSSO: 'css:button:has-text("GGGGGG|authorize.ContinuewithEnterpriseSSO|GGGGGG")'

dashboardLink: 'css:ul.flex>li:first-child>a'


continueWithEnterpriseSSOByText: 'text:GGGGGG|authorize.ContinuewithEnterpriseSSO|GGGGGG'


customerTestId: 'testId:directions'


